projects:
  amplifyDatasource:
    schemaPath: graphql/schema.json
    includes:
      - graphQLMyMINK
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: .
