-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggOMzcDSv67/52mGG
QD7F3CfcXgLfZOcXtvQxX6aVbpugCgYIKoZIzj0DAQehRANCAAR5WKBvAjqvJng5
+5Jl5eBrQ+wETZywnbv68JMe/5BhgvkDxctYz2i2oPABiy5wH2Ar4LERmZILdXDO
UljQRkBt
-----END PRIVATE KEY-----